#
# Copyright (C) 2010 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import build
import phony

env = build.Prepare(['libc'])
env.Append(LINKFLAGS = [ '-T', 'system/mips/mipssim/kernel.ld' ])
env.Program('kernel', [ Glob('*.c'), Glob('*.S') ])

phony.Targets(qemu = 'qemu-system-mipsel -kernel ' +
                     'build/mips/mipssim/system/kernel -M mipssim -serial stdio',
	      qemu_debug = 'qemu-system-mipsel -kernel ' +
			   'build/mips/mipssim/system/kernel -M mipssim -serial stdio -s -S')

